version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      - internal

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 15s
      timeout: 15s
      retries: 2

  cars-service:
    build: app/services/carsService
    image: ondubovickaya/cars-service
    container_name: cars-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATA_BASE_PORT: "5432"
      DATA_BASE_NAME: "postgres"
      DATA_BASE_USER: "postgres"
      DATA_BASE_PASS: "postgres"
      DATA_BASE_HOST: "postgres"
    ports:
      - "8070:8070"
    networks:
      - internal

  payments-service:
    build: app/services/paymentService
    image: ondubovickaya/payments-service
    container_name: payments-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATA_BASE_PORT: "5432"
      DATA_BASE_NAME: "postgres"
      DATA_BASE_USER: "postgres"
      DATA_BASE_PASS: "postgres"
      DATA_BASE_HOST: "postgres"
    ports:
      - "8050:8050"
    networks:
      - internal

  rental-service:
    build: app/services/rentalService
    image: ondubovickaya/rental-service
    container_name: rental-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATA_BASE_PORT: "5432"
      DATA_BASE_NAME: "postgres"
      DATA_BASE_USER: "postgres"
      DATA_BASE_PASS: "postgres"
      DATA_BASE_HOST: "postgres"
    ports:
      - "8060:8060"
    networks:
      - internal

  api-gateway:
    build: app/services/gatewayService
    image: ondubovickaya/api-gateway
    container_name: api-gateway
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      CARS_SERVICE_HOST: "cars-service"
      CARS_SERVICE_PORT: "8070"
      PAYMENT_SERVICE_HOST: "payments-service"
      PAYMENT_SERVICE_PORT: "8050"
      RENTAL_SERVICE_HOST: "rental-service"
      RENTAL_SERVICE_PORT: "8060"
    ports:
      - "8080:8080"
    networks:
      - internal
    
volumes:
  db-data:

networks:
  internal:
